<div class="slides"><section>
<?php
	//module/Application/view/application/auth/index.phtml:

	$title = 'Login';
	$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($this->translate($title)); ?></h1>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('auth', array('action' => 'index')));
	$form->prepare();

echo '<fieldset>';
	echo $this->form()->openTag($form);
	echo $this->formRow($form->get('username'));
	echo $this->formRow($form->get('password'));
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();
	echo "<a href=\"".$this->basePath().'/auth/create'."\">".$this->translate('Subscribe')."</a>";
	echo $this->form()->closeTag(); 
	echo "<div class=\"message\"><span style='color:red'>".$this->translate($this->message)."</span></div>";
	?>
</fieldset>
</div></section>
