<?php
 $title = 'Add new vehicule';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <table>
 <?php
 $form->setAttribute('vehicule', $this->url('vehicule', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo '<tr>
			<td>'.$this->formLabel($form->get('brand')).'</td>
			<td>'.$this->formInput($form->get('brand')).'</td>
	   </tr>';
 echo '<tr>
			<td>'.$this->formLabel($form->get('model')).'</td>
			<td>'.$this->formInput($form->get('model')).'</td>
	   </tr>';
 echo '<tr>
			<td>'.$this->formLabel($form->get('type')).'</td>
			<td>'.$this->formInput($form->get('type')).'</td>
	   </tr>';
 echo '<tr>
			<td>'.$this->formSubmit($form->get('submit')).'</td>
	   </tr>';
 echo $this->form()->closeTag();
 ?>
 </table>