<?php 
echo $this->doctype(); 

$auth = new \Zend\Authentication\AuthenticationService();
if ($auth->hasIdentity()) {
	$identity = $auth->getIdentity();
}
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Autoloc '. $this->translate('Location vehicule'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
	
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		  <!-- Brand and toggle get grouped for better mobile display -->
		  <div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			  <span class="sr-only">Toggle navigation</span>
			  <span class="icon-bar"></span>
			  <span class="icon-bar"></span>
			  <span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Autoloc</a>
		  </div>

		  <!-- Collect the nav links, forms, and other content for toggling -->
		  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<?php
						echo $this->navigation('navigation')
							->menu()
							->setUlClass('nav navbar-nav')
							->setMaxDepth(0)
							->render();
						?>
			<form class="navbar-form navbar-left" role="search">
			  <div class="form-group">
				<input type="text" class="form-control" placeholder="Search">
			  </div>
			  <button type="submit" class="btn btn-default">Rechercher</button>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<?php 
						if(isset($identity))
						{
							$statut = ($identity->right == 1)?' [admin]':'';
							$logoutUrl = $this->url('auth', array('action'=>'logout'));
							$rentUrl = $this->url('rent', array('action'=>'index'));
							echo '<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> '.$identity->username.''.$statut.'<b class="caret"></b></a>
									<ul class="dropdown-menu">
									  <li><a href="'.$rentUrl.'">Mes locations</a></li>
									  <li><a href="#">Mon compte</a></li>
									  <li><a href="#">Something else here</a></li>
									  <li class="divider"></li>
									  <li><a href="'.$logoutUrl.'">Log out</a></li>
									</ul>
								  </li>';
						}else{
							echo '<li><a href="'.$this->url('auth', array('action'=>'index')).'">Sign in</a></li>';
						}
					?>
				</li>
			  
			</ul>
		  </div><!-- /.navbar-collapse -->
		</nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Ferry Steve & Herrmann Matthieu <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
